import { CONTRACT_VERSION, type IntegrationErrorCode, type UnraidWatchIntegration } from "./contract";

/**
 * Transport for the UnraidWatch integration contract.
 *
 * This is the ONLY file in Nexus that knows how the contract is carried. Today
 * that is a Cloudflare Service Binding to the `unraidwatch-api` Worker, chosen
 * because both Workers live in the same account and it removes an entire class
 * of concerns (public URL, TLS, CORS, bearer headers in transit).
 *
 * Portability: to move off Cloudflare, replace the body of `unraidWatch()` with
 * an HTTP client that implements the same `UnraidWatchIntegration` interface.
 * Nothing else in Nexus — routes, DTOs, UI — needs to change.
 */

const KNOWN_CODES: readonly IntegrationErrorCode[] = [
  "unauthorized",
  "not_configured",
  "upstream_unavailable",
  "internal",
];

/**
 * `Env.UNRAIDWATCH` is generated by `wrangler types` from the `services` entry
 * in wrangler.jsonc. Wrangler types it as a bare `Service` because it cannot
 * know another repository's RPC surface, so `unraidWatch()` below is the single
 * place where we assert the contract.
 */
export type UnraidWatchEnv = Env;

/** Thrown when the integration reports a failure, carrying its stable code. */
export class IntegrationFailure extends Error {
  readonly code: IntegrationErrorCode;
  constructor(code: IntegrationErrorCode, message?: string) {
    super(message ?? code);
    this.name = "IntegrationFailure";
    this.code = code;
  }
}

/**
 * Verify that UnraidWatch speaks the contract version Nexus was built against.
 *
 * A mismatch means the two sides were deployed out of step. Failing loudly is
 * the point: silently rendering a payload whose field meanings may have changed
 * is worse than showing an error that names the fix.
 *
 * Only responses that actually carry a version can be checked — `identify()`
 * and `getOverview()`. Both are on the live path (every save, test and page
 * refresh), so a mismatch surfaces immediately. The granular per-section
 * methods return bare DTOs with no version field; they are reached only after
 * an overview has already validated the version.
 */
export function assertContractVersion(received: number | undefined): void {
  if (received !== CONTRACT_VERSION) {
    throw new IntegrationFailure(
      "internal",
      `unraidwatch_contract_mismatch:${received ?? "unknown"}:${CONTRACT_VERSION}`,
    );
  }
}

/**
 * Resolve the integration. Throws `unavailable` rather than returning null so
 * callers have exactly one error path.
 */
export function unraidWatch(env: UnraidWatchEnv): UnraidWatchIntegration {
  if (!env.UNRAIDWATCH) {
    throw new IntegrationFailure("internal", "unraidwatch_binding_missing");
  }
  return env.UNRAIDWATCH as unknown as UnraidWatchIntegration;
}

/**
 * Run an integration call, normalizing whatever the transport threw into an
 * `IntegrationFailure` with a stable code.
 *
 * UnraidWatch sets the thrown Error's `message` to the stable code precisely so
 * it survives transports that preserve only the message — Cloudflare RPC drops
 * the class and any custom properties.
 */
export async function callIntegration<T>(work: () => Promise<T>): Promise<T> {
  try {
    return await work();
  } catch (error) {
    if (error instanceof IntegrationFailure) throw error;
    const message = error instanceof Error ? error.message : "";
    const code = KNOWN_CODES.find((candidate) => candidate === message);
    if (code) throw new IntegrationFailure(code);
    // Transport-level failure (binding down, Worker not deployed, RPC error).
    throw new IntegrationFailure("upstream_unavailable", message || "unraidwatch_unreachable");
  }
}
