#!/usr/bin/env python3
"""Generate a safe Nexus D1 import from a NoteFlow D1 SQL export.

This tool is intentionally offline/read-only against the NoteFlow export. It never
connects to Cloudflare. It loads the export into an in-memory SQLite database,
extracts one tracker, and writes SQL that can later be inspected and executed
against Nexus D1.

Example:
  python tools/import-noteflow-tracker.py \
    ./noteflow-export.sql \
    --user-id user_123 \
    --tracker-id tr_99hdc6n92kz3 \
    --output ./noteflow-mental-health-import.sql
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

DEFAULT_TRACKER_ID = "tr_99hdc6n92kz3"
SOURCE = "noteflow"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("export", type=Path, help="Path to a full NoteFlow D1 SQL export")
    parser.add_argument("--user-id", required=True, help="Target Nexus users.id value")
    parser.add_argument("--tracker-id", default=DEFAULT_TRACKER_ID, help="NoteFlow tracker id to import")
    parser.add_argument("--output", type=Path, default=Path("noteflow-tracker-import.sql"), help="Generated Nexus SQL file")
    parser.add_argument("--report", type=Path, help="Optional JSON report path")
    return parser.parse_args()


def iso_from_unix(value: int) -> str:
    return datetime.fromtimestamp(int(value), tz=timezone.utc).isoformat().replace("+00:00", "Z")


def iso_date(value: int) -> str:
    return datetime.fromtimestamp(int(value), tz=timezone.utc).date().isoformat()


def sql_string(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def deterministic_id(namespace: str, *parts: str) -> str:
    digest = hashlib.sha256((namespace + "\x1f" + "\x1f".join(parts)).encode("utf-8")).hexdigest()[:32]
    return f"{digest[:8]}-{digest[8:12]}-{digest[12:16]}-{digest[16:20]}-{digest[20:32]}"


def load_export(path: Path) -> sqlite3.Connection:
    if not path.is_file():
        raise SystemExit(f"Export file not found: {path}")
    db = sqlite3.connect(":memory:")
    db.row_factory = sqlite3.Row
    try:
        db.executescript(path.read_text(encoding="utf-8"))
    except (UnicodeDecodeError, sqlite3.Error) as exc:
        raise SystemExit(f"Could not load NoteFlow export: {exc}") from exc
    return db


def ensure_source_tables(db: sqlite3.Connection) -> None:
    required = {"tracker_subjects", "tracker_notes", "tracker_conversations"}
    existing = {
        row[0]
        for row in db.execute("SELECT name FROM sqlite_master WHERE type='table'")
    }
    missing = required - existing
    if missing:
        raise SystemExit(f"NoteFlow export is missing required tables: {', '.join(sorted(missing))}")


def fetch_tracker(db: sqlite3.Connection, tracker_id: str) -> sqlite3.Row:
    row = db.execute(
        "SELECT id, name, instructions, context_summary, created_at, updated_at "
        "FROM tracker_subjects WHERE id = ?",
        (tracker_id,),
    ).fetchone()
    if not row:
        raise SystemExit(f"Tracker not found in export: {tracker_id}")
    return row


def fetch_notes(db: sqlite3.Connection, tracker_id: str) -> list[sqlite3.Row]:
    return list(
        db.execute(
            "SELECT id, content, created_at, updated_at FROM tracker_notes "
            "WHERE tracker_id = ? ORDER BY created_at, id",
            (tracker_id,),
        )
    )


def fetch_messages(db: sqlite3.Connection, tracker_id: str) -> tuple[list[sqlite3.Row], list[sqlite3.Row], int]:
    rows = list(
        db.execute(
            "SELECT id, role, content, created_at FROM tracker_conversations "
            "WHERE tracker_id = ? ORDER BY created_at, id",
            (tracker_id,),
        )
    )
    user_messages: list[sqlite3.Row] = []
    assistant_messages: list[sqlite3.Row] = []
    auto_duplicates = 0
    for row in rows:
        role = str(row["role"] or "")
        content = str(row["content"] or "")
        if role == "user" and content.startswith("[Auto] New entry:"):
            auto_duplicates += 1
            continue
        if role == "user":
            user_messages.append(row)
        elif role == "assistant":
            assistant_messages.append(row)
    return user_messages, assistant_messages, auto_duplicates


def render_sql(
    user_id: str,
    tracker: sqlite3.Row,
    notes: Iterable[sqlite3.Row],
    user_messages: Iterable[sqlite3.Row],
    assistant_messages: Iterable[sqlite3.Row],
) -> str:
    lines: list[str] = [
        "-- Generated by tools/import-noteflow-tracker.py",
        f"-- Source tracker: {tracker['name']} ({tracker['id']})",
        "-- Review this file before executing it against Nexus D1.",
        "PRAGMA foreign_keys = ON;",
        "",
    ]

    for row in notes:
        source_id = str(row["id"])
        created = iso_from_unix(row["created_at"])
        updated = iso_from_unix(row["updated_at"] or row["created_at"])
        journal_id = deterministic_id("nfj", str(tracker["id"]), source_id)
        lines.extend([
            "INSERT OR IGNORE INTO journal_entries",
            "  (id, user_id, entry_date, body, created_at, updated_at)",
            "VALUES (",
            f"  {sql_string(journal_id)}, {sql_string(user_id)}, {sql_string(iso_date(row['created_at']))},",
            f"  {sql_string(str(row['content'] or ''))}, {sql_string(created)}, {sql_string(updated)}",
            ");",
            "",
        ])

    for role, rows in (("user", user_messages), ("assistant", assistant_messages)):
        for row in rows:
            source_message_id = str(row["id"])
            legacy_id = deterministic_id("nfl", str(tracker["id"]), source_message_id)
            created = iso_from_unix(row["created_at"])
            lines.extend([
                "INSERT OR IGNORE INTO journal_legacy_messages",
                "  (id, user_id, source, source_tracker_id, source_message_id, role, body, created_at)",
                "VALUES (",
                f"  {sql_string(legacy_id)}, {sql_string(user_id)}, {sql_string(SOURCE)}, {sql_string(str(tracker['id']))},",
                f"  {sql_string(source_message_id)}, {sql_string(role)}, {sql_string(str(row['content'] or ''))}, {sql_string(created)}",
                ");",
                "",
            ])

    lines.extend([
        f"DELETE FROM journal_ai_state WHERE user_id = {sql_string(user_id)};",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    db = load_export(args.export)
    ensure_source_tables(db)
    tracker = fetch_tracker(db, args.tracker_id)
    notes = fetch_notes(db, args.tracker_id)
    user_messages, assistant_messages, auto_duplicates = fetch_messages(db, args.tracker_id)

    if not notes:
        raise SystemExit("Refusing to generate an empty import: tracker has no notes")

    output = render_sql(args.user_id, tracker, notes, user_messages, assistant_messages)
    args.output.write_text(output, encoding="utf-8")

    report = {
        "tracker": {"id": tracker["id"], "name": tracker["name"]},
        "journalEntries": len(notes),
        "legacyUserMessages": len(user_messages),
        "legacyAssistantMessages": len(assistant_messages),
        "autoDuplicateMessagesSkipped": auto_duplicates,
        "firstEntry": iso_from_unix(notes[0]["created_at"]),
        "lastEntry": iso_from_unix(notes[-1]["created_at"]),
        "output": str(args.output),
    }
    if args.report:
        args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
